// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package sims

const (
	Version = "v1.0.4"
	GitCommit = "2352f67" // the commit JUST BEFORE the release
	VersionDate = "2020-04-22 00:57" // UTC
)

