// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package sims

const (
	Version     = "v1.3.3"
	GitCommit   = "ad8a154"          // the commit JUST BEFORE the release
	VersionDate = "2023-02-15 11:24" // UTC
)
