// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package sims

const (
	Version = "v1.2.3"
	GitCommit = "201f070" // the commit JUST BEFORE the release
	VersionDate = "2020-12-30 10:11" // UTC
)

