// Code generated by "stringer -linecomment -output=strings.go -type=StepGrain,StopStepCond,ContextModel"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Cycle-0]
	_ = x[Quarter-1]
	_ = x[AlphaMinus-2]
	_ = x[AlphaFull-3]
	_ = x[SGTrial-4]
	_ = x[TrialBlock-5]
	_ = x[Condition-6]
	_ = x[StepGrainN-7]
}

const _StepGrain_name = "CycleQuarterAlphaMinusAlphaFullTrialBlockConditionStepGrainN"

var _StepGrain_index = [...]uint8{0, 5, 12, 22, 31, 36, 41, 50, 60}

func (i StepGrain) String() string {
	if i < 0 || i >= StepGrain(len(_StepGrain_index)-1) {
		return "StepGrain(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StepGrain_name[_StepGrain_index[i]:_StepGrain_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SSNone-0]
	_ = x[SSTrialNameMatch-1]
	_ = x[SSTrialNameNonmatch-2]
	_ = x[StopStepCondN-3]
}

const _StopStepCond_name = "NoneTrial NameNot Trial NameStopStepCondN"

var _StopStepCond_index = [...]uint8{0, 4, 14, 28, 41}

func (i StopStepCond) String() string {
	if i < 0 || i >= StopStepCond(len(_StopStepCond_index)-1) {
		return "StopStepCond(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StopStepCond_name[_StopStepCond_index[i]:_StopStepCond_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ELEMENTAL-0]
	_ = x[CONJUNCTIVE-1]
	_ = x[BOTH-2]
	_ = x[ContextModelN-3]
}

const _ContextModel_name = "ELEMENTALCONJUNCTIVEBOTHContextModelN"

var _ContextModel_index = [...]uint8{0, 9, 20, 24, 37}

func (i ContextModel) String() string {
	if i < 0 || i >= ContextModel(len(_ContextModel_index)-1) {
		return "ContextModel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContextModel_name[_ContextModel_index[i]:_ContextModel_index[i+1]]
}
