// Code generated by "stringer -type=LearnType"; DO NOT EDIT.

package main

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Hebbian-0]
	_ = x[ErrorDriven-1]
	_ = x[LearnTypeN-2]
}

const _LearnType_name = "HebbianErrorDrivenLearnTypeN"

var _LearnType_index = [...]uint8{0, 7, 18, 28}

func (i LearnType) String() string {
	if i < 0 || i >= LearnType(len(_LearnType_index)-1) {
		return "LearnType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LearnType_name[_LearnType_index[i]:_LearnType_index[i+1]]
}

func (i *LearnType) FromString(s string) error {
	for j := 0; j < len(_LearnType_index)-1; j++ {
		if s == _LearnType_name[_LearnType_index[j]:_LearnType_index[j+1]] {
			*i = LearnType(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: LearnType")
}
