// Code generated by "stringer -type=LearnType"; DO NOT EDIT.

package main

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

const _LearnType_name = "PureHebbPureErrorHebbErrorLearnTypeN"

var _LearnType_index = [...]uint8{0, 8, 17, 26, 36}

func (i LearnType) String() string {
	if i < 0 || i >= LearnType(len(_LearnType_index)-1) {
		return "LearnType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LearnType_name[_LearnType_index[i]:_LearnType_index[i+1]]
}

func (i *LearnType) FromString(s string) error {
	for j := 0; j < len(_LearnType_index)-1; j++ {
		if s == _LearnType_name[_LearnType_index[j]:_LearnType_index[j+1]] {
			*i = LearnType(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: LearnType")
}
