# Copyright (c) 2019, The Emergent Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SGWordTrans = {
    "threwtossed": "threw",
    "threwhosted": "threw",
    "drovetrans":  "drove",
    "drovemotiv":  "drove",
    "shedv":       "shed",
    "shedn":       "shed",
    "rosev":       "rose",
    "rosen":       "rose",
    "pitcherpers": "pitcher",
    "pitchercont": "pitcher",
    "batball":     "bat",
    "batanim":     "bat",
    "ballsphere":  "ball",
    "ballparty":   "ball",
}

SGWords = [
    "consumed",
    "ate",
    "drank",
    "stirred",
    "spread",
    "kissed",
    "gave",
    "hit",
    "threw",
    "drove",
    "shed",
    "rose",
    "someone",
    "adult",
    "child",
    "dog",
    "busdriver",
    "teacher",
    "schoolgirl",
    "pitcher",
    "spot",
    "something",
    "food",
    "steak",
    "soup",
    "icecream",
    "crackers",
    "jelly",
    "icedtea",
    "koolaid",
    "utensil",
    "spoon",
    "knife",
    "finger",
    "kitchen",
    "livingroom",
    "park",
    "bat",
    "ball",
    "bus",
    "fur",
    "gusto",
    "pleasure",
    "daintiness",
    "with",
    "in",
    "to",
    "by",
    "was",
    "start",
]

SGRoles = [
    "Agent",
    "Action",
    "Patient",
    "Instrument",
    "CoAgent",
    "CoPatient",
    "Location",
    "Adverb",
    "Recipient",
]

SGFillers = [
    "Consumed",
    "Ate",
    "Drank",
    "Stirred",
    "Spread",
    "Kissed",
    "Gave",
    "Hit",
    "ThrewTossed",
    "ThrewHosted",
    "DroveTrans",
    "DroveMotiv",
    "ShedV",
    "ShedN",
    "RoseV",
    "RoseN",
    "Someone",
    "Adult",
    "Child",
    "Dog",
    "Busdriver",
    "Teacher",
    "Schoolgirl",
    "PitcherPers",
    "PitcherCont",
    "Spot",
    "Something",
    "Food",
    "Steak",
    "Soup",
    "Icecream",
    "Crackers",
    "Jelly",
    "Icedtea",
    "Koolaid",
    "Utensil",
    "Spoon",
    "Knife",
    "Finger",
    "Kitchen",
    "Livingroom",
    "Park",
    "BatBall",
    "BatAnim",
    "BallSphere",
    "BallParty",
    "Bus",
    "Fur",
    "Gusto",
    "Pleasure",
    "Daintiness",
    "None",
    "Ex1", # adding extras so it has 55 units to match layer size
    "Ex2",
    "Ex3",
]

SGAmbigVerbs = [
    "consumed",
    "threw",
    "drove",
]

SGAmbigNouns = [
    "someone",
    "adult",
    "child",
    "dog",
    "something",
    "food",
    "utensil",
]

# these are somewhat ambiguous but in syntax and context not really
SGSemiAmbigNouns = [
    "pitcher",
    "bat",
    "ball",
]
