// Code generated by go-bindata. DO NOT EDIT.
// sources:
// digits.dat

package main


import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}


type asset struct {
	bytes []byte
	info  fileInfoEx
}

type fileInfoEx interface {
	os.FileInfo
	MD5Checksum() string
}

type bindataFileInfo struct {
	name        string
	size        int64
	mode        os.FileMode
	modTime     time.Time
	md5checksum string
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) MD5Checksum() string {
	return fi.md5checksum
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _bindataDigitsdat = []byte(
	"\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x84\xd1\xb1\x4e\xc4\x30\x0c\xc6\xf1\xb9\x3c\x07\x6c\x1d\x1c\xc7\xc9\x41" +
	"\x84\x98\x18\x60\xe1\x05\x50\x75\x62\x60\x04\x31\xc0\xfb\x23\x65\xc1\xff\xc4\xe1\xd4\xe1\xfc\x35\xd7\x5f\xec\xe4" +
	"\xfc\xd4\xb6\xeb\x97\xb7\x8f\xf7\xed\xe6\xf9\xf3\xeb\xe7\xfb\x55\x9b\xec\x72\xdc\x6b\x3b\xed\xe5\xc1\xbf\x4c\x87" +
	"\x4f\x8a\x94\x91\xcc\xa5\xb4\x0b\x52\x42\x52\xa4\x8c\xe4\x15\x85\xa2\x50\x14\x8a\x42\x51\x28\x19\x4a\x86\x92\xa1" +
	"\x64\x28\x19\x8a\x41\x31\x28\x06\xc5\xa0\x18\x94\x02\xa5\x40\x29\x50\x0a\x94\x02\xa5\x42\xa9\x50\x2a\x94\x0a\xa5" +
	"\xee\x76\x5c\x9d\x1f\xdb\x26\xfd\x49\xee\x37\x21\x47\xd5\xf8\x1f\xd9\xa4\x5b\xc9\x3d\x5e\x9d\xab\x78\x0f\x6f\xe9" +
	"\xa4\x8d\x92\x4c\x2b\xec\xb0\xe7\x6e\xe5\xbf\xcc\xae\xd1\x11\xdf\xcc\x56\xea\x96\x85\xdf\xc7\x93\xff\x33\x65\xb7" +
	"\xca\xc5\xbe\xc6\x55\x56\xbe\xaf\x1a\x5a\x09\xd3\x8d\x56\x70\x9a\xdd\x3a\x2d\x76\x5c\xd5\xa3\xe2\xfb\xba\x5d\xf4" +
	"\xb5\x9e\x71\x7d\x8f\x77\xc1\x9d\xcb\x74\x5e\x82\xa9\x23\xeb\x37\x00\x00\xff\xff\x42\xcf\xac\x9a\xf3\x04\x00\x00" +
	"")

func bindataDigitsdatBytes() ([]byte, error) {
	return bindataRead(
		_bindataDigitsdat,
		"digits.dat",
	)
}



func bindataDigitsdat() (*asset, error) {
	bytes, err := bindataDigitsdatBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{
		name: "digits.dat",
		size: 1267,
		md5checksum: "",
		mode: os.FileMode(420),
		modTime: time.Unix(1566673137, 0),
	}

	a := &asset{bytes: bytes, info: info}

	return a, nil
}


//
// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
//
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
}

//
// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
// nolint: deadcode
//
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

//
// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or could not be loaded.
//
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
}

//
// AssetNames returns the names of the assets.
// nolint: deadcode
//
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

//
// _bindata is a table, holding each asset generator, mapped to its name.
//
var _bindata = map[string]func() (*asset, error){
	"digits.dat": bindataDigitsdat,
}

//
// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
//
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, &os.PathError{
					Op: "open",
					Path: name,
					Err: os.ErrNotExist,
				}
			}
		}
	}
	if node.Func != nil {
		return nil, &os.PathError{
			Op: "open",
			Path: name,
			Err: os.ErrNotExist,
		}
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}


type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{Func: nil, Children: map[string]*bintree{
	"digits.dat": {Func: bindataDigitsdat, Children: map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
