// Code generated by "core generate -add-types"; DO NOT EDIT.

package main

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "main.EnvTypes", IDName: "env-types", Doc: "EnvTypes are the types of train / test environments."})

var _ = types.AddType(&types.Type{Name: "main.Config", IDName: "config", Doc: "Config has config parameters related to running the sim", Fields: []types.Field{{Name: "NRuns", Doc: "total number of runs to do when running Train"}, {Name: "NEpochs", Doc: "total number of epochs per run"}, {Name: "TestInterval", Doc: "how often to run through all the test patterns, in terms of training epochs.\ncan use 0 or -1 for no testing."}}})

var _ = types.AddType(&types.Type{Name: "main.Sim", IDName: "sim", Doc: "Sim encapsulates the entire simulation model, and we define all the\nfunctionality as methods on this struct.  This structure keeps all relevant\nstate information organized and available without having to pass everything around\nas arguments to methods, and provides the core GUI interface (note the view tags\nfor the fields which provide hints to how things should be displayed).", Methods: []types.Method{{Name: "SetEnv", Doc: "SetEnv select which set of patterns to train or test on", Directives: []types.Directive{{Tool: "types", Directive: "add"}}, Args: []string{"envType"}}}, Fields: []types.Field{{Name: "Lrate", Doc: "Lrate is the learning rate; .04 is default 'cortical' learning rate.\nTry lower levels to see how low you can go and still get priming."}, {Name: "Decay", Doc: "Decay is the proportion of activation decay between trials."}, {Name: "EnvType", Doc: "EnvType is the environment type; Use the Env button (SetEnv) to set."}, {Name: "Config", Doc: "Config contains misc configuration parameters for running the sim"}, {Name: "Net", Doc: "the network -- click to view / edit parameters for layers, paths, etc"}, {Name: "Params", Doc: "network parameter management"}, {Name: "TrainAll", Doc: "All training patterns"}, {Name: "TrainA", Doc: "A training patterns"}, {Name: "TrainB", Doc: "B training patterns"}, {Name: "Loops", Doc: "contains looper control loops for running sim"}, {Name: "Stats", Doc: "contains computed statistic values"}, {Name: "Logs", Doc: "Contains all the logs and information about the logs.'"}, {Name: "Envs", Doc: "Environments"}, {Name: "Context", Doc: "leabra timing parameters and state"}, {Name: "ViewUpdate", Doc: "netview update parameters"}, {Name: "GUI", Doc: "manages all the gui elements"}, {Name: "RandSeeds", Doc: "a list of random seeds to use for each run"}}})
