// Code generated by "stringer -type=TestType"; DO NOT EDIT.

package main

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MultiObjs-0]
	_ = x[StdPosner-1]
	_ = x[ClosePosner-2]
	_ = x[ReversePosner-3]
	_ = x[ObjAttn-4]
	_ = x[TestTypeN-5]
}

const _TestType_name = "MultiObjsStdPosnerClosePosnerReversePosnerObjAttnTestTypeN"

var _TestType_index = [...]uint8{0, 9, 18, 29, 42, 49, 58}

func (i TestType) String() string {
	if i < 0 || i >= TestType(len(_TestType_index)-1) {
		return "TestType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TestType_name[_TestType_index[i]:_TestType_index[i+1]]
}

func (i *TestType) FromString(s string) error {
	for j := 0; j < len(_TestType_index)-1; j++ {
		if s == _TestType_name[_TestType_index[j]:_TestType_index[j+1]] {
			*i = TestType(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: TestType")
}
